language: cpp

branches:
  only:
    - master

install:
  - sudo pip install codecov
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libgtest-dev
  - mkdir build_gtest
  - cd build_gtest
  - cmake /usr/src/gtest
  - sudo make
  - sudo cp libgtest* /usr/lib
  - cd ..


script:
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - ./Test
  - cd ..
  - doxygen Doxyfile

addons:
  apt:
    packages:
      - lcov
      - doxygen

after_success:
  # Create lcov report
  - lcov --capture --directory ./CMakeFiles/Test.dir/ --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info # debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master